[package]
name = "lib"
version = "0.1.0"
authors = ["Aarav Mehta"]
edition = "2021"
description = "A library to interact with the different API's of GA4GH"
license = "Apache-2.0"
repository = "https://github.com/elixir-cloud-aai/ga4gh-sdk.git"

[dependencies]

[lib]
name = "my_project"
path = "lib/src/lib.rs"