services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-autogen-models
    image: ga4gh-sdk-autogen-models
    container_name: ga4gh-sdk-autogen-models
    volumes:
      - .:/app
    working_dir: /app
    command: [ "sleep", "infinity" ]
    init: true
