name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: rustup update stable
    - name: Build models
      run: ./build-models.sh
    - name: Build
      run: cargo build --verbose
    - name: Run custom tests
      run: ./run-tests.sh
    - name: Run tests
      run: cargo test --verbose
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Format
      run: cargo fmt -- --check
